name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: EditorConfig Lint
      uses: docker://mstruebing/editorconfig-checker:2.7.2

    - name: Install
      run: |
        yarn config set ignore-engines true
        yarn

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: |
        yarn test > COVERAGE_RESULT
        echo "$(cat COVERAGE_RESULT)"

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
