name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: EditorConfig Lint
      uses: docker://mstruebing/editorconfig-checker:4.0.1

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Codecov
      if: matrix.node-version == 24
      uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
